### ISSUE TITLE
Clarify whether CIS can be used

### ISSUE THREAD

**Issue by AkechiShiro** [JeremiahSecrist/regula-nix#8]
- [ ] Contact CIS regarding the subjects below 
  - [ ] Ask them if they can give us a machine-readable format of Distribution Independent Linux
  - [ ] Permission to use their content/re-licensing issues
- [X] Contact OVH about Debian-CIS
  - [X] Ask if their content could be used/re-licensed, see issue : https://github.com/ovh/debian-cis/issues/218 (waiting for their answer)
- [ ] Identify if all scripts at https://github.com/ovh/debian-cis/tree/master/bin/hardening have a certain structure that could be parsed to extract only the relevant configuration/checks in a scripted way in order to transition them into checks more Nix oriented.

**Comment by JeremiahSecrist** [comment]
CIS has also not gotten back to be involving the usage of the benchmark documentation. But given debian-CIS exists it could be used as precedent.

**Comment by JeremiahSecrist** [comment]
Also I would like to point out [lynis](https://github.com/CISOfy/lynis) exists. its license is very close it MIT apache v3. something to look into.
